server:
  port: 80
   
#mybatis-plus配置 
mybatis-plus:
  mapper-locations:
    - classpath:com.aikbc.pandora.mapper/*.xml
  type-aliases-package: com.aikbc.pandora.entity
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

#关闭thymeleaf缓存,否则开发修改html需重启服务    
spring:
  thymeleaf:
    cache: false
